version: '{build}'
skip_tags: true
image: Visual Studio 2019
install:
build_script:
  - pwsh: ./AzureSecretCheck/Build.ps1
test: off
artifacts:
  - path: ./AzureSecretCheck/artifactsSeq.App.*.nupkg
deploy:
  - provider: NuGet
    api_key:
      secure: oy2pm5bq5ciro7jlwcgqyhiusvb7phxefinri77yjoxxui
    skip_symbols: true
    on:
      branch: /^(master|dev)$/
  - provider: GitHub
    auth_token:
      secure: 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
    artifact: /Seq.App.*\.nupkg/
    tag: v$(appveyor_build_version)
    on:
      branch: master