version: '{build}'
skip_tags: true
image: Visual Studio 2019
install: []
build_script:
  - pwsh: ./Build.ps1
test: false
artifacts:
  - path: artifacts/Seq.App.*.nupkg
deploy:
  - provider: NuGet
    api_key:
      secure: c6jcGMZQBTnCVDeTPL98SvLFu6ogzoi1aKUj+xqu6c/QQkuVu2viHjEtntFkQyEX
    skip_symbols: true
    on:
      branch: /^(master|dev)$/
  - provider: GitHub
    auth_token:
      secure: 8+tt+poihs1fGyYzVOCvjEnuA5FRdK9M1XFkR5viPXAjYbYunUB+3/nI6ecA5eo1
    artifact: /Seq.App.*\.nupkg/
    tag: v$(appveyor_build_version)
    on:
      branch: master