version: '{build}'
skip_tags: true
image: Visual Studio 2019
install:
build_script:
  - pwsh: ./Build.ps1
test: off
artifacts:
  - path: artifacts/Seq.App.*.nupkg
deploy:
  - provider: NuGet
    api_key:
      secure: c6jcGMZQBTnCVDeTPL98SvLFu6ogzoi1aKUj+xqu6c/QQkuVu2viHjEtntFkQyEX
    skip_symbols: true
    on:
      branch: /^(master|dev)$/
  - provider: GitHub
    auth_token:
      secure: s58s6pu8sRbX0Z68CbdHk0Wt/qvkJVpoW0UqJ6KZXmO+D9NO7mQInItZWiEgKNgn
    artifact: /Seq.App.*\.nupkg/
    tag: v$(appveyor_build_version)
    on:
      branch: master