version: '{build}'
skip_tags: true
image: Visual Studio 2019
install:
build_script:
  - pwsh: ./AzureSecretCheck/Build.ps1
test: off
artifacts:
  - path: ./AzureSecretCheck/artifacts/Seq.App.*.nupkg
deploy:
  - provider: NuGet
    api_key:
      secure: vZnLzFhEXOsqoHlMS2HNwJtLISd3ZTlMcqKqxononATy/1C7a4uHNl+p0yMSxEQ8
    skip_symbols: true
    on:
      branch: /^(master|dev)$/
  - provider: GitHub
    auth_token:
      secure: s58s6pu8sRbX0Z68CbdHk0Wt/qvkJVpoW0UqJ6KZXmO+D9NO7mQInItZWiEgKNgn
    artifact: /Seq.App.*\.nupkg/
    tag: v$(appveyor_build_version)
    on:
      branch: master